[package]
name = "ntex-grpc"
version = "0.1.0"
license = "MIT"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "GRPC Client/Server framework"
documentation = "https://docs.rs/ntex-grpc"
repository = "https://github.com/ntex-rs"
readme = "README.md"
keywords = ["grpc"]
categories = ["asynchronous", "network-programming"]
edition = "2018"

[lib]
name = "ntex_grpc"
path = "src/lib.rs"

[dependencies]
ntex-h2 = "0.1"
ntex-http = "0.1"
ntex-connect = "0.1"
ntex-io = "0.1"
ntex-util = "0.1.17"
ntex-bytes = "0.1.15"
ntex-service = "0.3"
ntex-rt = "0.4"

ntex-prost-derive = "0.10.1"

async-trait = "0.1.0"
bitflags = "1.3"
prost = "0.10"
slab = "0.4.2"
log = "0.4"
pin-project-lite = "0.2"
thiserror = "1.0"

[dev-dependencies]
env_logger = { version = "0.9", default-features = false }
openssl = "0.10"
ntex = { version = "0.5", features = ["openssl", "tokio"] }
ntex-tls = { version = "0.1", features = ["openssl"] }
ntex-connect = { version = "0.1", features = ["openssl", "tokio"] }
