[package]
name = "ntex-grpc"
version = "0.5.0"
license = "MIT"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "GRPC Client/Server framework"
documentation = "https://docs.rs/ntex-grpc"
repository = "https://github.com/ntex-rs/ntex-grpc"
readme = "README.md"
keywords = ["grpc"]
categories = ["asynchronous", "network-programming"]
edition = "2018"

[lib]
name = "ntex_grpc"
path = "src/lib.rs"

[dependencies]
ntex-h2 = "0.4.4"
ntex-http = "0.1.10"
ntex-connect = "0.3.2"
ntex-io = "0.3.6"
ntex-util = "0.3.4"
ntex-bytes = "0.1.21"
ntex-service = "1.2.7"
ntex-rt = "0.4"
ntex-grpc-derive = "0.4.0"

log = "0.4"
thiserror = "1.0"
pin-project-lite = "0.2"

[dev-dependencies]
openssl = "0.10"
ntex = { version = "0.7.5", features = ["openssl", "tokio"] }
ntex-tls = { version = "0.3.1", features = ["openssl"] }
ntex-connect = { version = "0.3.2", features = ["openssl", "tokio"] }
env_logger = { version = "0.10", default-features = false }
