[workspace]
members = [
  "ntex-grpc",
  "ntex-grpc-codegen",
  "examples/helloworld"
]

[patch.crates-io]
ntex-grpc = { path = "./ntex-grpc" }
ntex-grpc-codegen = { path = "./ntex-grpc-codegen" }

ntex-h2 = { git = "https://github.com/ntex-rs/ntex-h2.git" }
