[workspace]
members = [
  "ntex-grpc",
  "ntex-grpc-codegen",
  "prost-build",
  "prost-derive",
  "examples/custom",
  "examples/helloworld"
]

[patch.crates-io]
ntex-grpc = { path = "./ntex-grpc" }
ntex-grpc-codegen = { path = "./ntex-grpc-codegen" }
ntex-grpc-derive = { path = "./prost-derive" }

ntex-prost-build = { path = "./prost-build" }
