[workspace]
members = [
  "ntex-grpc",
  "ntex-grpc-codegen",
  "examples/helloworld"
]

[patch.crates-io]
ntex-grpc = { path = "./ntex-grpc" }
ntex-grpc-codegen = { path = "./ntex-grpc-codegen" }

ntex-h2 = { path = "../ntex-h2" }
ntex = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-http = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-bytes = { path = "../../ntex/ntex-bytes" }
